name: library

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: rebar3 compile

  # On macOS and Windows, the EGL dependency will need the location of ANGLE
  # libraries and headers (which we specify via environment variables).
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: rebar3 compile

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: rebar3 compile
        shell: pwsh
